### ISSUE TITLE
Updating pm.max_children 

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#122]
Hey,

So I have been getting this on php-fpm output

> 
[11-Aug-2017 13:17:46] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it

Is it possible for me to overwrite this setting in the php-ini-overrides.ini or do I have to do something else.
Where is the php-ini-overrides.ini being included? (can't seem to locate it on the php-fpm server)

**Comment by luispabon** [comment]
Hmm typically you'd go on scale horizontally when you're going over that limit.

You cannot set that on php.ini as it's a php-fpm setting; external to php itself as it were. You can indeed override however by mounting some extra fpm config in the container.

  * Download this https://raw.githubusercontent.com/phpdocker-io/base-images/master/php/7.1/fpm/overrides.conf somewhere into your project
  * Add `pm.max_children = whatever` on the `[www]` section
  * Add a volume on the php-fpm section on your docker-compose overlaying this file on top of the original, like so:

```yaml
    php-fpm:
      build: phpdocker/php-fpm
      container_name: something
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./path-to-override-conf:/etc/php/7.1/fpm/pool.d/z-overrides.conf
```
