### ISSUE TITLE
Add support for Mail Catcher

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#130]
In a recent project I had to send emails and I really benefited from having something like [MailCatcher](https://mailcatcher.me/).
Here is what I had to add to docker-compose.yml.

```
    mailcatcher:
      image: schickling/mailcatcher:latest
      container_name: projectname-mailcatcher
      working_dir: /application
      ports:
       - "1080:1080"
```

Your app will now only have to use mailcatcher as the smtp server with port 1025 and you are done.
