### ISSUE TITLE
Connect to MySQL throws error table performance_schema.session_status does not exist

### ISSUE THREAD

**Issue by Mondane** [phpdocker-io/phpdocker.io#135]
Just generated a fresh docker.yml and tried to connect to the MySQL server. This didn't work, the following error was thrown:

> SQL Error 1146: Table 'performance_schema.session_status' doesn't exist.

How can I fix this?

I have this configuration, no changes to the generated one:

```yml
###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: dweh-php71-mysql57-mailhog
      ports:
        - "1026:8025"

    mysql:
      image: mysql:5.7
      container_name: dweh-php71-mysql57-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=dweh
        - MYSQL_USER=vaarties-sites
        - MYSQL_PASSWORD=vaarties-sites
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: dweh-php71-mysql57-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: dweh-php71-mysql57-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
```
