### ISSUE TITLE
 Add support for PHPUnit and XDebug with PHPStrom

### ISSUE THREAD

**Issue by boscho87** [phpdocker-io/phpdocker.io#151]
:+1:

**Comment by dzschille** [comment]
I made for me this config:

*phpdocker/php-fpm/php-ini-overrides.ini*
```
xdebug.remote_enable=1
xdebug.remote_autostart=0
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.profiler_enable=0
xdebug.profiler_enable_trigger=1
xdebug.profiler_output_dir="/application/var/log"
```

*docker-compose.yml*
```
php-fpm:
    environment:
        XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
        PHP_IDE_CONFIG: "serverName=Projectname"
```

*.env.dist*
`
DOCKER_HOST_IP=172.21.0.1
`

*README.md*
```
Xdebug is installed and configured. If it does not work for you, check if the in docker-compose.yml defined host IP
is for your system correct. You can see your host IP with:

        ## open console in webserver
        docker-compose exec webserver /bin/sh
        
        ## view your host IP
        /sbin/ip route|awk '/default/ { print $3 }'
        
        ## leave the container console
        exit

Now take this IP and set it in .env as value **DOCKER_HOST_IP**. Then you have to stop and start your docker containers again.
```

If nobody has a better solution, i could create a PR.

**Comment by holodny** [comment]
Beautiful!  How is your local code set up?  Do you do a bind to a local directory?  Thanks for sharing!

**Comment by luispabon** [comment]
@dzschille that's great stuff. If you feel brave, do feel free to create a PR as work is not leaving me with a lot of spare time to work on this.

**Comment by dzschille** [comment]
@holodny I use the standard output file from the phpdocker generator. My Symfony project has its web root in [public/](http://symfony.com/doc/current/best_practices/creating-the-project.html).

When you start debugging your project in PhpStorm for the first time you will be asked if you want to "use path mappings" for the server. Activate it and map the project root to "/application". That should be enough for debugging. You find [information about settting the path mappings here](https://confluence.jetbrains.com/display/PhpStorm/Zero-configuration+Web+Application+Debugging+with+Xdebug+and+PhpStorm#Zero-configurationWebApplicationDebuggingwithXdebugandPhpStorm-Troubleshooting).

**Comment by boscho87** [comment]
:thumbsup

**Comment by holodny** [comment]
Thanks, Dzschille.  I began setting up a project to test (I'm using Codeigniter).  It's at https://github.com/holodny/docker_codeigniter_lemp .

It runs but setting up the debugging (xdebug) is evading me still.

**Comment by dzschille** [comment]
@holodny how do you try to start your debug session? 
I open my application in the browser, activate the debug button of the [Xdebug-Helper](https://github.com/BrianGilbert/xdebug-helper-for-firefox) and than reload the page or click an action button of my application.

**Comment by holodny** [comment]
@dzschille  Yah, I'm using Xdebug-helper as well.  (I thin set a break point in the controller using IntelliJ and refresh the browser).  I'm using Xdebug with Codeigniter/Nginx/PHP locally in a more conventional setup on my local machine but now I'm adding IntelliJ's Docker integration to the mix as well (I should probably try it without Docker integration first, actually and just treat it as a conventional remote server).

I'm using your settings above.  Since Codeigniter doesn't have an env.dist file, I tried hard-coding the URL.  I'm going to keep trying.  Everything but debug and mapping to the application in the URL is working perfectly now.  Currently, the URL I use for the application is "localhost:8074/People" rather than "localhost:8074/docker-codeigniter-lemp/People".

**Comment by luispabon** [comment]
I'd be very interested to know how you guys manage to set up PhpStorm as well as the docker-compose environment - I'm not a heavy xdebug user beyond code coverage.

**Comment by holodny** [comment]
@luispabon I put images of my (some of them being best guess) IntelliJ configurations in my github repository at https://github.com/holodny/docker_codeigniter_lemp .   This includes for IntelliJ Docker integration.  I use Xdebug a lot in my conventional local setup for regular debugging, along with SQL Tracker in Toad (or its SQL Developer equivalent).  Phpdocker.io is awesome!  I've been using Spring Initializr and having a similar tool for Docker/PHP is great.

**Comment by dzschille** [comment]
@holodny , i had no problem to debug your Codeigniter sample app. I have writen a HowTo as a issue in your repo: https://github.com/holodny/docker_codeigniter_lemp/issues/1

**Comment by dzschille** [comment]
@luispabon , i still like to create a PR, but i can not start this application properly, see #152.

**Comment by luispabon** [comment]
👍 sorry mate, hadn't seen that issue

**Comment by sergiodebcn** [comment]
I tried this config from a mac, but i cant connect xdebug

**Comment by thafirstone** [comment]
Neither do I. My xdebug won't work with phpStorm on my mac. Can someone help me please ?

**Comment by cve** [comment]
HI guys,

I'm trying to setup xdebug 3.0.2 with this configuration:

php-ini-overrides.ini
```ini
xdebug.idekey=PHPSTORM
xdebug.mode=debug
```
docker-compose.yaml
```yml
[...]
    php-fpm:
        build: phpdocker/php-fpm
        container_name: marketer-php-fpm
        working_dir: /application
        environment:
            XDEBUG_CONFIG: "client_host=${WSLIP}"
[...]
```

`${WSLIP}` is dynamic ip which is set in .bashrc like that:
```bash
export WSLIP=$(ifconfig $(route -n | grep ^0.0.0.0 | awk '{print $NF}') | grep inet | grep -v inet6 | awk '{print $2}')
```

when I run it I see in php-fpm logs:
```
marketer-php-fpm | NOTICE: PHP message: Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 172.17.35.79:9003 (through xdebug.client_host/xdebug.client_port) :-(
```

what am I doing wrong? https://stackoverflow.com/a/65355354/985270 with this post it should work.... I tried set discover_client_host=1 in xdebug with no luck :(

**Comment by dzschille** [comment]
@cve is the IP from the log the correct one? Please check it with 
`docker-compose exec webserver /bin/sh -c "/sbin/ip route|awk '/default/ { print $3 }'"`

**Comment by cve** [comment]
The command:
```
docker-compose exec webserver /bin/sh -c "/sbin/ip route|awk '/default/ { print $3 }'"
```
returns 172.26.0.1

so, now I hardcode it in `XDEBUG_CONFIG: "client_host=172.26.0.1"` and in request logs I have:
```
NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.26.0.1:9003 (through xdebug.client_host/xdebug.client_port) :-(
```

**Comment by cve** [comment]
my full docker-compose.yml file:
```yml
###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
        image: mailhog/mailhog:latest
        container_name: project-mailhog
        ports:
            - "1025:8025"

    mariadb:
        image: mariadb:10.4
        container_name: project-mariadb
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=project
            - MYSQL_DATABASE=project
            - MYSQL_USER=project
            - MYSQL_PASSWORD=project
        ports:
            - "3307:3306"

    webserver:
        image: nginx:alpine
        container_name: project-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php-fpm:
        build: phpdocker/php-fpm
        container_name: project-php-fpm
        working_dir: /application
        environment:
            XDEBUG_CONFIG: "client_host=172.26.0.1"
            PHP_IDE_CONFIG: "serverName=PHPSTORM"
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    node:
        image: node:10-alpine
        container_name: project-node
        volumes:
            - .:/application
        ports:
            - "8086:8080"
        working_dir: /application
        command: ["npm", "run", "dev"]
```

**Comment by dzschille** [comment]
@cve do you have in your _php-ini-overrides.ini_ the setting `xdebug.remote_autostart=1` ? If yes the this explanation: https://stackoverflow.com/a/65264131/1823551

**Comment by LeoWie93** [comment]
I am on Windows and could fix this issue by setting the remote and client host to `host.docker.internal`. Should work for mac aswell.


![image](https://user-images.githubusercontent.com/29427760/109158932-4d328400-7774-11eb-8614-d64657e88656.png)

**Comment by dzschille** [comment]
@LeoWie93 thanks, good to know! I'm on Ubuntu so that doesn't work for me. That's my settings:
```
xdebug.remote_enable=1
xdebug.remote_autostart=0
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.profiler_enable=0
xdebug.profiler_enable_trigger=1
xdebug.profiler_output_dir="/application/var/log"
```

**Comment by cve** [comment]
@LeoWie93 thanks, but now I have:
```NOTICE: PHP message: Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(```

**Comment by boscho87** [comment]
@cve 

what ports have you set there:
![image](https://user-images.githubusercontent.com/11815871/109166835-6be94880-777d-11eb-83cb-7240f33b7296.png)

did you configure the firewall? > there should be a MS Windows Popup, when you click on the "start to listen" button in phpunit.

**Comment by cve** [comment]
This is my config, and how can I check firewall config? Noting appears when I click Start Listening...

![image](https://user-images.githubusercontent.com/594384/109167845-7ce68980-777e-11eb-801b-ef61a8fae522.png)

**Comment by cve** [comment]
I am on wsl2 with x server in windows, but I think, it's never mind

**Comment by luispabon** [comment]
I've never run wsl or wsl2 so I'm not entirely sure, but I believe wsl2 runs in a hyper-v virtual machine does it not? So the host ip, from the point of view of docker, will be that of the virtual machine and not your computer.

**Comment by dzschille** [comment]
@cve [two years ago](https://github.com/phpdocker-io/phpdocker.io/issues/151#issuecomment-364557913) i have linked to this [step by step explanation](https://github.com/programetica/docker_codeigniter_lemp/issues/1). Perhaps it helps you.

**Comment by cve** [comment]
@dzschille Thank you for that guide, but... It not work... When it should display "dialog" for accept connection it does nothing and in logs I have:
`NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.26.0.1:9003 (through xdebug.client_host/xdebug.client_port) :-(`

I'm using xdebug 3.0.2, but Is it important? Configuration looks similar...

Command `docker-compose exec webserver /bin/sh -c "/sbin/ip route|awk '/default/ { print \$3 }'"` returns `172.26.0.1` so I set it in my docker-compose.yml

Even if I try this setup on fresh Symfony project, there is no connection 😭 phpinfo() looks ok, but connection not work...

This is my whole setup:

```ini
upload_max_filesize = 100M
post_max_size = 108M

xdebug.idekey=PHPSTORM
xdebug.mode=debug
xdebug.client_port=9003
```

```yml
###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
        image: mailhog/mailhog:latest
        container_name: marketer-mailhog
        ports:
            - "1025:8025"

    mariadb:
        image: mariadb:10.4
        container_name: marketer-mariadb
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=marketer
            - MYSQL_DATABASE=marketer
            - MYSQL_USER=marketer
            - MYSQL_PASSWORD=marketer
        ports:
            - "3307:3306"

    webserver:
        image: nginx:alpine
        container_name: marketer-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php-fpm:
        build: phpdocker/php-fpm
        container_name: marketer-php-fpm
        working_dir: /application
        environment:
            XDEBUG_CONFIG: "client_host=172.26.0.1"
            PHP_IDE_CONFIG: "serverName=docker"
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    node:
        image: node:10-alpine
        container_name: marketer-node
        volumes:
            - .:/application
        ports:
            - "8086:8080"
        working_dir: /application
        command: ["npm", "run", "dev"]
```

```Dockerfile
FROM phpdockerio/php72-fpm:latest
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php7.2-mysql php7.2-sqlite php7.2-xdebug php7.2-gd php7.2-intl php7.2-yaml \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
```

```conf
server {
    listen 80 default;

    client_max_body_size 108M;

    access_log /var/log/nginx/application.access.log;


    root /application/public;
    index index.php;

    if (!-e $request_filename) {
        rewrite ^.*$ /index.php last;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
    }
    
}
```
This is my Debug config in PhpStorm
![image](https://user-images.githubusercontent.com/594384/109270203-fd080000-780d-11eb-811c-95297e32db6a.png)
This is my Server config in PhpStorm
![image](https://user-images.githubusercontent.com/594384/109270252-0beeb280-780e-11eb-9c17-d8f2c306d558.png)
This is my interpreter config in PhpStorm
![image](https://user-images.githubusercontent.com/594384/109270294-1b6dfb80-780e-11eb-8a9e-eab781df9d07.png)
This is my PHP config in PhpStorm
![image](https://user-images.githubusercontent.com/594384/109270341-2de83500-780e-11eb-827b-435c47965bb1.png)
This is output from phpinfo() about xdebug properly installed:
![image](https://user-images.githubusercontent.com/594384/109272138-c089d380-7810-11eb-8847-0464652f3beb.png)

I have Docker for Windows configured with WSL2 with Ubuntu and I'm running PhpStorm from Ubuntu by Xserver in Windows (with that setup project have faster resopnses from filesystem and there is no problems with path like \\wsl$\ for setup PHPUnit etc.)
