### ISSUE TITLE
Add support supervisor (queue)

### ISSUE THREAD

**Issue by yanlinaung30** [phpdocker-io/phpdocker.io#162]
- Is there any support for supervisor configuration in laravel?

**Comment by luispabon** [comment]
No, but you could add another service to your docker-compose file, like so

```yaml
    queue-worker:
      build: phpdocker/php-fpm
      container_name: project-queue-worker
      working_dir: /application
      volumes:
        - .:/application
      command: ["php", "artisan", "queue:work", "sqs", "--sleep=3", "--tries=3"]
      restart_policy:
        condition: on-failure
```

This will use the same container image with all your extensions and override fpm to use artisan instead. Docker will take care of restarting the process if it fails (`restart_policy`, you can change `on-failure` to `any` if you want it restarted regardless of its exit status).

Let me know if this works and I'll have a look at adding this to the generator.

**Comment by yanlinaung30** [comment]
@luispabon It works!  As I have supervisor config file. I updated as of the following.
```
    queue-worker:
      build: phpdocker/php-fpm
      container_name: project-queue-worker
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      command: bash -c "supervisord -c /etc/supervisor/supervisord.conf && php artisan queue:restart"
      restart: on-failure
```
**supervisor and python-pip are also installed from Dockerfile**
`&& apt-get -y install git supervisor python-pip\`
