### ISSUE TITLE
Need a guide for setting up xDebug on VSCode using php7.3-fpm

### ISSUE THREAD

**Issue by luizjr** [phpdocker-io/phpdocker.io#217]
Hi @luispabon, I need a guide for setting up xDebug on VSCode using php7.3-fpm

I haven't found anything explaining with this version yet.

**Comment by vinser** [comment]
Sorry for late posting. I use this files and it works.
**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/application/": "${workspaceRoot}"
            },
            "hostname": "localhost"
        }
    ]
}
```
**docker-compose.yml**
```
version: "3.1"
services:

  webserver:
    image: nginx:alpine
    container_name: popds-webserver
    working_dir: /application
    volumes:
        - ./:/application
        - ./LNPP/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: always

  php-fpm:
    build: LNPP/php-fpm
    container_name: popds-php-fpm
    working_dir: /application
    volumes:
      - ./:/application
      - ./LNPP/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./LNPP/php-fpm/xdebug-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/20-overrides.ini
    restart: always
```
**php-ini-overrides.ini**
```
upload_max_filesize = 100M
post_max_size = 100M
```
**xdebug-ini-overrides.ini**
```
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = host.docker.internal
xdebug.remote_port = 9000

; xdebug.idekey=VSCODE

```
