### ISSUE TITLE
Configuration for PHP5.6 no longer works

### ISSUE THREAD

**Issue by queenvictoria** [phpdocker-io/phpdocker.io#221]
Hi there. I recently needed to work on an ancient site that doesn't support PHP7.x. 

Loading up the site I noticed 500 errors.

Running phpinfo I noticed that PHP was 7.7

SSh into the container.

```
root@:/application# apt-get update && apt-get -y --no-install-recommends install php5-mysql
...
Package php5-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-mysql' has no installation candidate
```

However 5.6 is available

```
root@:/application# apt-get remove -y php7*
root@:/application# apt-get update && apt-get -y --no-install-recommends install php5.6-fpm php5.6-mysql
...
# mkdir -p /run/php 
# echo "/usr/sbin/php-fpm5.6 -F -O 2>&1 | sed -u 's,.*: \"\(.*\)$,\1,'| sed -u 's,\"$,,' 1>&1" > /usr/bin/php-fpm
```

Can we update the config please?

**Comment by luispabon** [comment]
What base image are you using?

**Comment by queenvictoria** [comment]
H @luispabon Looks like it's not defined.

`docker-compose.yml`

```
###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: test56-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=database
        - MYSQL_USER=username
        - MYSQL_PASSWORD=password
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: test56-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test56-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

```

`phpdocker/php-fpm/Dockerfile`

```
FROM phpdockerio/php56-fpm:latest
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php5-mysql \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
```
