### ISSUE TITLE
Connection reset by peer php 7.4

### ISSUE THREAD

**Issue by abr4xas** [phpdocker-io/phpdocker.io#231]
This is related to #164 

```
lvl2-mysql   |  2020/07/24 05:15:02 [error] 6#6: *1 recv() failed (104: Connection reset by peer) while
 reading response header from upstream, client: 192.168.64.1, server: , 
request: "POST /nova-api/articles?editing=true&editMode=create HTTP/1.1", 
upstream: "fastcgi://192.168.64.3:9000", host: "localhost", 
referrer: "http://localhost/nova/resources/articles/new"
```

```
lvl2-mysql   | 2020-07-24T05:15:02.270374Z 3 [Note] Aborted connection 3 to 
db: 'blog' user: 'blog' host: '192.168.64.3' (Got an error reading communication packets)
```

My log file: [abr4xas/8ed0f4f829e391bfa209da964d6250da](https://gist.github.com/abr4xas/8ed0f4f829e391bfa209da964d6250da)

docker-compose.yml

```
version: "3.1"
services:

    mysql:
      image: mysql:5.7.31
      container_name: lvl2-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=blog
        - MYSQL_USER=blog
        - MYSQL_PASSWORD=blog
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: lvl2-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: lvl2-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
``` 

Application type: `Generic: Symfony 4, Zend, Laravel, Lumen...`

![image](https://user-images.githubusercontent.com/405484/88363222-a7d6ae00-cd55-11ea-9e00-415023357764.png)

**EDIT**

I'm using Ubuntu 18.04.4 LTS

```bash
docker images|grep phpdockerio/php74
phpdockerio/php74-fpm                latest                    98f529fdd0a7        3 weeks ago         182MB
```
New image after `docker-compose build --pull`

Now:

```bash
→ docker images|grep phpdockerio/php74
phpdockerio/php74-fpm             latest                    74db87f9f6d2        12 hours ago        182MB
phpdockerio/php74-fpm             <none>                    98f529fdd0a7        3 weeks ago         182MB
```

Docker file for php

```bash
FROM phpdockerio/php74-fpm:latest
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php7.4-mysql php7.4-gd php7.4-soap \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
```
