### ISSUE TITLE
XDebug connection closed

### ISSUE THREAD

**Issue by svanschu** [phpdocker-io/phpdocker.io#347]
I'm afraid I couldn't get xdebug to work with VSC.

It seems that it has something like a connection because the hostet webapplication loads forever. But vcs only reports "connection closed"

What I'm doing wrong? I thought I followed the documentation correctly.

![image](https://github.com/phpdocker-io/phpdocker.io/assets/806395/1c2fb5a5-2371-47a8-8739-bd3da98a5d1f)

compose file
```
webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '43000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
```

Added to php-ini-override.conf

```
xdebug.mode = debug
xdebug.remote_connect_back = true
xdebug.start_with_request = yes
```

VCS launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Listen for XDebug Docker",
            "type": "php",
            "request": "launch",

            // Server Remote XDebug Port - 9000 is the default XDebug port
            "port": 43000,

            // Server Remote Path -> Local Project Path
            "pathMappings": {
                "/application/public/schuweb-sitemap-dev-j4": "${workspaceRoot}/public/schuweb-sitemap-dev-j4"
            },
            "hostname": "localhost"
        }
    ]
}
```
