### ISSUE TITLE
How to connect to MySQL with e.g. HeidiSQL

### ISSUE THREAD

**Issue by Mondane** [phpdocker-io/phpdocker.io#68]
I've tried connecting to localhost:3306 but without succes. I've also tried the hostname mentioned in the README.html, still no success. How can I connect with e.g. HeidiSQL to the docker?

**Comment by luispabon** [comment]
Mondane, you need to use the connection settings generated for you on the readme file. Localhost 3306 will never be mapped to docker-mysql on phpdocker.io generated environments.

If `localhost` doesn't work, try connecting to your loopback adress (eg `127.0.0.1`) instead. This is dependent on whether you're running Docker natively, or under Vagrant.

**Comment by Mondane** [comment]
Thank you, that gave me a pointer and I fixed it by adding ports to the Mysql part in the *docker-compose.yml* :

```yml
php56-mysql56-mysql:
  image: mysql:5.6
  container_name: php56-mysql56-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db
    - MYSQL_USER=usr
    - MYSQL_PASSWORD=pwd
  ports:
    - "1027:3306"
```

I can now connect to the database on localhost:1027 with usr:pwd
